
COPY conf/ /opt/docker/

USER root

RUN set -x \
    && apk-install \
        make \
        autoconf \
        g++ \
    && pecl install xdebug \
    && apk del -f --purge \
        autoconf \
        g++ \
        make \
    && docker-php-ext-enable xdebug \
    && docker-run-bootstrap \
    && docker-image-cleanup

USER application
