domain: moethennessyvietnam-com-vn.myshopify.com
api_key: 5c5f088b636cfc36f0211ab6dce66078
password: ''
shared_secret: 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
_core:
  default_config_hash: udKj72CZ_w3BDHIhs60liLXO-9YBbxRwn7PVsFt9x7M
